language: python
python: 2.7
services: postgresql
install: pip install -r requirements.txt
cache: pip
before_script:
  - psql -c "CREATE DATABASE ss_db;" -U postgres
  - psql -c "CREATE ROLE sudoku_solver WITH PASSWORD '';" -U postgres
  - psql -c "ALTER ROLE sudoku_solver WITH LOGIN;" -U postgres
  - psql -c "ALTER USER sudoku_solver WITH SUPERUSER;" -U postgres
script:
  - flake8 .
  - coverage run manage.py test -v 2
  - coverage report
