language: python
python: 2.7
services: postgresql
install: pip install -r requirements.txt
cache: pip
before_script:
  - psql -c "CREATE DATABASE ss_db;" -U postgres
  - psql -c "CREATE ROLE sudoku_solver WITH PASSWORD '';" -U postgres
script: python manage.py test
