# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('possibilities', models.CharField(max_length=9)),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuPuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsolved_puzzle', models.CharField(blank=True, max_length=200)),
                ('solved_puzzle', models.CharField(max_length=200)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
