# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 00:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sudoku_solver.utils


class Migration(migrations.Migration):

    replaces = [(b'solver', '0001_initial'), (b'solver', '0002_auto_20160807_2154'), (b'solver', '0003_auto_20160812_0346'), (b'solver', '0004_auto_20160812_0403'), (b'solver', '0005_auto_20160812_0415'), (b'solver', '0006_auto_20160812_0419'), (b'solver', '0007_sudokupuzzle_missing_vals_pos'), (b'solver', '0008_auto_20161123_0046'), (b'solver', '0009_auto_20161123_0056'), (b'solver', '0010_auto_20161207_2310'), (b'solver', '0011_auto_20161215_1046'), (b'solver', '0012_auto_20161216_1041'), (b'solver', '0013_auto_20161216_1048'), (b'solver', '0014_auto_20170102_2301'), (b'solver', '0015_auto_20170102_2328'), (b'solver', '0016_auto_20170111_1041'), (b'solver', '0017_auto_20170114_1414')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('possibilities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9)),
                ('filled', models.BooleanField(default=False)),
                ('col', models.IntegerField(blank=True, default=-1)),
                ('row', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuPuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsolved_puzzle', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=9), size=9)),
                ('solved_puzzle', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9), blank=True, default=[], null=True, size=9)),
                ('solved', models.BooleanField(default=False)),
                ('missing_vals_pos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=None, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='puzzlecell',
            name='puzzle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solver.SudokuPuzzle'),
        ),
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=sudoku_solver.utils.get_empty_list, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9),
        ),
    ]
