# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='solved_puzzle',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='unsolved_puzzle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
