# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_squashed_0017_auto_20170114_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokupuzzle',
            name='solving_time',
            field=models.FloatField(default=0.0),
        ),
    ]
