# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 01:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_sudokupuzzle_solving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='missing_vals_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2), blank=True, null=True, size=None),
        ),
    ]
