# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_auto_20160807_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlecell',
            name='position',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='puzzlecell',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
