# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_auto_20160812_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
