# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_auto_20160812_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzlecell',
            old_name='puzzle_id',
            new_name='puzzle_pk',
        ),
    ]
