# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0005_auto_20160812_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=models.CharField(blank=True, default='[]', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puzzlecell',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
