# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0007_sudokupuzzle_missing_vals_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlecell',
            name='position',
        ),
        migrations.AddField(
            model_name='puzzlecell',
            name='x_pos',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='puzzlecell',
            name='y_pos',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
