# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0008_auto_20161123_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzlecell',
            old_name='x_pos',
            new_name='col',
        ),
        migrations.RemoveField(
            model_name='puzzlecell',
            name='y_pos',
        ),
        migrations.AddField(
            model_name='puzzlecell',
            name='row',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
