# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 23:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0009_auto_20161123_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='solved_puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9), blank=True, default=[], null=True, size=9),
        ),
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='unsolved_puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=9), size=9),
        ),
    ]
