# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0011_auto_20161215_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlecell',
            name='puzzle_pk',
        ),
        migrations.AddField(
            model_name='puzzlecell',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solver.SudokuPuzzle'),
        ),
    ]
