# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0012_auto_20161216_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecell',
            name='puzzle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solver.SudokuPuzzle'),
        ),
    ]
