# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 23:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import sudoku_solver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0013_auto_20161216_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='missing_vals_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=sudoku_solver.utils.get_empty_list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='solved_puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=sudoku_solver.utils.get_empty_list, null=True, size=9), blank=True, default=sudoku_solver.utils.get_empty_list, null=True, size=9),
        ),
    ]
