# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 23:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import sudoku_solver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0014_auto_20170102_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=sudoku_solver.utils.get_empty_list, null=True, size=9),
        ),
    ]
