# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0015_auto_20170102_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlecell',
            name='possibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9),
        ),
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='missing_vals_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='solved_puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=9), blank=True, default=[], null=True, size=9),
        ),
    ]
