# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0016_auto_20170111_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='missing_vals_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=None, null=True, size=None),
        ),
    ]
